  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ian-dev-444015/wfp-nyc-image:$COMMIT_SHA', '-f', 'deploy/Dockerfile', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ian-dev-444015/wfp-nyc-image:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'wfp-nyc'
    - '--image'
    - 'gcr.io/ian-dev-444015/wfp-nyc-image:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
  
  images:
  - 'gcr.io/ian-dev-444015/wfp-nyc-image:$COMMIT_SHA'
  
  options:
    logging: CLOUD_LOGGING_ONLY